name: Conventional Commits Lint

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Run the Webiny Conventional Commits action
      - name: Lint commits
        uses: webiny/action-conventional-commits@v1.0.3
